### ISSUE TITLE
General Driver Updates

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#166]
### What is the expected enhancement?

#147 also suggest some general improvements to the drivers. The implementation of these is tracked by this issue:

- [x] relocate `qiskit_nature.drivers.*` into `qiskit_nature.drivers.second_quantization.*`
- [x] relocate `qiskit_nature.transformers.*` into `qiskit_nature.transformers.second_quantization.*`
- [x] check the "file"-based drivers for general improvements:
  - [x] `fcidumpd`
  - [x] `hdf5d`
- [x] check the "program"-based drivers for general improvements:
  - [x] `pyscfd`
  - [x] `pyquanted`
  - [x] `psi4d`
  - [x] `gaussiand`

While performing the checks for general improvments we should also check for the ability of the driver to perform more input validation and update the documentation of all methods.

**Comment by mrossinek** [comment]
With #173 nearing its merging and #180 following suite shortly after, two major (and the most important) steps of this issue will be addressed soon. None of the other drivers are technically high priority right now because none of them immediately block other implementations planned in the near future.
Nonetheless, all driver codes should be checked in order to determine what kind of updates are possible and to estimate the time such updates would take on a case by case basis. Most drivers are likely to undergo very little changes because besides PySCF all but one other driver are not interfacing another Python-based code, limiting the code complexity which could be updated in a similar style to #180.

**Comment by mrossinek** [comment]
As part of migrating the new drivers to the property framework (#264) I have checked each open driver for an estimated amount of time required to refactor it. I will summarize below:

| Driver | Estimated Time required |
|-|-|
| pyscf | Done and fully migrated after #264 |
| pyquante | very similar to PySCF, portable in 0.5-1 days |
| psi4 | relies on `hdf5` framework (see below) |
| gaussian (electronic) | relies on `gauopen` module, mostly Property integration required, (maybe some function reorganization), portable in 0.5-1 days |
| gaussian (vibrational + log) | relies on `GaussianLogResult`, portable in 0.5-1 days |
| fcidump | basically done after #264 |
| hdf5 | requires more discussion (#302) |

The migration of the remaining drivers will likely not be part of the `0.2.0` release.

**Comment by mrossinek** [comment]
A quick update on this epic:
- [ ] `pyquante`: handled by #525 
- [ ] `psi4`: handled by #521 (blocked by #461)
- [ ] `gaussian`: prepared offline (blocked by #461 and #521 [latter due to minor general refactoring in that PR])
- [ ] `hdf5`: prepared offline (blocked by #461)

**Comment by pbark** [comment]
I am moving this epic back to product backlog until we have completed the hdf5 and the rest of the drivers updates.
