### ISSUE TITLE
`ElectronicDensity` enhancements

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit-nature#919]
### What is the expected enhancement?

The new `ElectronicDensity` property is very naive in its current form. It was intended to be a starting point for further improvements, some ideas I will be listing below.

- [ ] renormalization techniques based on expected quantities, for example particle number, spin, etc.
    - this may become particularly important once implementing algorithms iterating over the `ElectronicDensity`. The noise we incur when measuring these expectation values on a quantum device can hinder convergence of such algorithms significantly
- [ ] symmetry-recovery (similar problem as in the above)
- more initialization methods, for example:
    - [ ] based purely on number of spatial orbitals and particle number
    - [ ] `ElectronicDensity.zero`
    - [ ] `ElectronicDensity.identity`
